#!/usr/bin/env python3
"""The neural reel: the game re-rendered by a diffusion model, a depth network and a detector
graded against the renderer's own truth, the level repainted, with Claude choosing the looks.
Run scripts/neural-setup.py first (or let this script do it) so the models are loaded."""
from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("reel", os.path.join(HERE, "demo-reel.py"))
reel = importlib.util.module_from_spec(spec); spec.loader.exec_module(reel)
caption, director, state, wait_for, graph, tool, node_id, link_id, connect = reel.caption, reel.director, reel.state, reel.wait_for, reel.graph, reel.tool, reel.node_id, reel.link_id, reel.connect


def claude(prompt: str) -> subprocess.Popen:
    return subprocess.Popen([os.path.join(reel.REPO, "director.sh"), prompt], cwd=reel.REPO, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def claude_node_name(before_ids: set) -> str:
    """The display name of the newest node Claude added, minus its prefix."""
    names = [n["display_name"] for n in graph()["nodes"] if n["id"] not in before_ids and str(n["display_name"]).startswith("Claude")]
    return names[-1].split(":", 1)[-1].strip() if names else ""


def main() -> int:
    caption("", "")
    director(command="mission", goal="patrol"); director(command="style", style="photoreal"); director(command="give", item="everything")
    time.sleep(1.0)
    # Claude starts thinking about the looks while the opening plays; its first node lands mid-way.
    ids_before = {n["id"] for n in graph()["nodes"]}
    style_before = state().get("style")
    proc = claude("Look at the game and pick three very different visual styles for the diffusion re-render — your choice, be bold, name them yourself as free-text prompts. "
                  "Apply each with add_processor: a DirectorCommand named 'Claude: <two-word style name>' with command style and your prompt in the style field, waiting 9 seconds between them. "
                  "Then reply in two short sentences: what you saw, and why you chose those three.")
    caption("DOOM, RE-RENDERED BY A DIFFUSION MODEL. LIVE.", "sd-turbo + ControlNet in its own process · 1993 on the left, what it dreams on the right")
    time.sleep(7)
    caption("GEOMETRY-LOCKED BY THE RENDERER'S OWN DEPTH", "the depth channel the renderer writes anyway is the ControlNet's conditioning · same GPU frame, no copy")
    time.sleep(6)
    caption("CLAUDE IS PICKING THE LOOKS", "claude -p on the desktop · MCP into this node · it chooses, it applies, its words are on screen")
    for k in range(3):
        if wait_for(lambda: state().get("style") != style_before, 75 if k == 0 else 30):
            style_before = state().get("style")
            time.sleep(1.0)
            name = claude_node_name(ids_before) or str(style_before)[:30]
            caption(f"CLAUDE: {name.upper()[:36]}", "chosen and applied by Claude · every frame re-imagined, geometry locked to the game")
            time.sleep(6)
    wait_for(lambda: proc.poll() is not None, 3)

    # Claude thinks about a material while the perception beats play.
    ids_before = {n["id"] for n in graph()["nodes"]}
    repaint_before = state().get("repaint")
    proc = claude("Pick one material or look for the level's walls and floors — something surprising and vivid — and repaint the level with it: add_processor a DirectorCommand named "
                  "'Claude: <material>' with command repaint and the material in the style field. Reply in two short sentences: what the level looked like, and what you turned it into.")
    caption("NEURAL DEPTH, GRADED AGAINST THE TRUTH — LIVE", "Depth Anything V2 on the RGB · the renderer knows the real depth · the error is on screen, every frame")
    time.sleep(8)
    caption("A DETECTOR ASKED FOR MONSTERS, GRADED BY THE RENDERER", "Grounding DINO · green: what it found · red: labelled monsters it missed · hit rate live")
    director(command="spawn", kind="zombieman", count=2, where="ahead")
    time.sleep(8)
    try:
        for target, port in (("Planner", "detections_from_upstream"), ("Telemetry", "detections_from_upstream")):
            cut = link_id("Perceive", target, port)
            if cut:
                tool("disconnect", link_id=cut)
            connect("Detector", "detections_to_downstream", target, port)
        caption("SWAPPED LIVE: THE ROBOT NOW FIGHTS FROM THE LEARNED DETECTOR", "the oracle link is cut, Grounding DINO's detections feed the planner · no restart")
    except Exception as failure:
        print("swap skipped:", failure, flush=True)
    time.sleep(7)
    director(command="heal")
    caption("CLAUDE IS REPAINTING THE LEVEL", "new wall and floor textures generated by the model, quantized to Doom's palette, patched into the running renderer")
    if wait_for(lambda: state().get("repaint") != repaint_before, 60):
        wait_for(lambda: False, 4)  # the generation itself takes a few seconds
        name = claude_node_name(ids_before) or str(state().get("repaint")).split("#")[0]
        caption(f"REPAINTED BY CLAUDE: {name.upper()[:30]}", "generated, dithered into the 1993 palette, written into the atlas the renderer samples · the diffusion view follows")
        time.sleep(9)
    wait_for(lambda: proc.poll() is not None, 3)

    caption("ONE GPU · FOUR NEURAL NETS · A 60 FPS GAME · ONE GRAPH", "diffusion, depth, detection, generation — each its own process on the same frame · the runtime recorded this")
    time.sleep(6)
    caption("github.com/tatolab/streamlib-doom", "StreamLib · every box its own process · every link a shared GPU frame")
    time.sleep(5)
    caption("", "")
    return 0


if __name__ == "__main__":
    sys.exit(main())
